export const START_LOAD = 'START_LOAD';
export const STOP_LOAD = 'STOP_LOAD';
export const LOGGED_IN = 'LOGGED_IN';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';